# Generated by Django 5.0.1 on 2024-01-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca_consulta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meses',
        ),
    ]
